print("Bienvenido a phyton 🐍")
print("######Cartel 6°B######")
print("######Programando######")
print("######ESTUDIANDO######")
print("######APRENDIENDO######")
print("#SE CRREAN PROYECTOS#")
print("🤑👦🏿👦🏿🥲🥲😁😲😭😭🥶🥵🌞😊🥲")
print("#                                  #")
print("##LA PALABRA DEL DIA ES##")
print("EL CONOCIMIENTO ES PODER 👦🏿")
print("ENTONCES APLIQUEMOSLO😭")
print("BIENVENIDO CICLO 2025-2026")